name: spicy
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=2.19.6 <3.0.0'



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  animate_do: ^3.0.2
  smooth_page_indicator: ^1.1.0
  liquid_swipe: ^3.1.0
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/onboarding/
    - assets/images/background/
    - assets/images/logo/
    - assets/icons/


  fonts:
    - family: Bruno
      fonts:
        - asset: assets/fonts/bruno/BrunoAceSC-Regular.ttf
    #
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico/Pacifico-Regular.ttf